# Generated by Django 6.1.1 on 2026-10-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
    ]
