# Generated by Django 6.1.1 on 2026-10-01 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_style', models.CharField(max_length=100)),
                ('budget_level', models.CharField(max_length=50)),
                ('walking_preference', models.BooleanField(default=False)),
                ('culture', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('nature', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('nightlife', models.BooleanField(default=False)),
                ('family_friendly', models.BooleanField(default=False)),
                ('solo_travel', models.BooleanField(default=False)),
                ('include_weather', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='destinations.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'destination')},
            },
        ),
    ]
