# Generated by Django 6.1.1 on 2026-10-04 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_remove_attraction_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month number from 1 (January) to 12 (December)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('avg_temperature', models.DecimalField(decimal_places=2, help_text='Average temp for this month', max_digits=5)),
                ('avg_feels_like', models.DecimalField(decimal_places=2, max_digits=5)),
                ('typical_condition', models.CharField(help_text='e.g., Sunny, Rainy, Snow', max_length=100)),
                ('avg_humidity', models.IntegerField()),
                ('avg_wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_uv_index', models.DecimalField(decimal_places=1, max_digits=4)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='destinations.destination')),
            ],
            options={
                'ordering': ('month',),
                'unique_together': {('destination', 'month')},
            },
        ),
    ]
